services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_DB: galaxy_empire
      POSTGRES_USER: galaxy_user
      POSTGRES_PASSWORD: galaxy_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

  # galaxy-empire:
  #   build: .
  #   ports:
  #     - '4001:3000'
  #   environment:
  #     DATABASE_URL: postgres://galaxy_user:galaxy_password@db:5432/galaxy_empire
  #     ORIGIN: http://192.168.1.107:4001
  #   depends_on:
  #     - db

volumes:
  postgres_data:
