services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: galaxy_user
      POSTGRES_PASSWORD: galaxy_password
      POSTGRES_DB: galaxy_empire
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  galaxy-empire:
    build: .
    ports:
      - '4001:3000'
    environment:
      DATABASE_URL: postgres://galaxy_user:galaxy_password@db:5432/galaxy_empire
      ORIGIN: http://192.168.1.107:4001
    depends_on:
      - db

volumes:
  postgres_data:
